#!/usr/bin/env bash
cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

azure_upload() {
  cli_log "Starting - Backup to Azure"
  cd $BACKUP_DIR
  az storage blob upload --container-name $BLOB_BACKUP_CONTAINER \
    --file $APP/$APP-$TIMESTAMP.tar.gz \
    --name $APP/$APP-$TIMESTAMP.tar.gz
  cli_log "Completed - Backup to Azure"
  rm -rf $APP/$APP-$TIMESTAMP.tar.gz
  cli_log "Clean local files - Backup to Azure"
}
