#!/usr/bin/env bash
set -e
. "$CLI_WORKDIR/common"

cli_help_confluence() {
  echo "
Command: confluence

Usage:
  confluence  Take backup for confluence server(self-hosted)"
  exit 1
}

[ ! -n "$2" ] && cli_help_confluence
if [ "$2" == "-h" ]; then
  cli_help_confluence
fi

if [ ! -d $BACKUP_DIR/$APP ]; then
  mkdir -p $BACKUP_DIR/$APP;
fi

APP=$1
TIMESTAMP=`date "+%d-%b-%y_%H-%M-%S"`
DAILY_BACKUP=$BACKUP_DIR/$APP/$APP-$TIMESTAMP

if [ ! -d $DAILY_BACKUP ]; then
  mkdir -p $DAILY_BACKUP;
fi
#DB DUMP
cli_log "Taking DB Dump"
mysqldump -u $CDB_USERNAME -p$CDB_PASSWORD $CDB_NAME > $DAILY_BACKUP/$APP.sql
cli_log "DB DUMP done."
#HOME DIR BACKUP
cli_log "Backing up Home directory"
tar cvzf $DAILY_BACKUP/home-dir.tar.gz /var/atlassian/application-data/$APP
#INSTALLATION DIR BACKUP
cli_log "Backing up Install directory"
tar cvzf $DAILY_BACKUP/install.tar.gz /opt/atlassian/$APP
cli_log "ZIPing backup directory"
cd $BACKUP_DIR/$APP && tar cvzf $APP-$TIMESTAMP.tar.gz $APP-$TIMESTAMP
rm -rf $DAILY_BACKUP
cli_log "Backup Complete"
