#!/usr/bin/env bash
set -e
. "$CLI_WORKDIR/common"

cli_help_gitlab() {
  echo "
Command: gitlab

Usage:
  gitlab  Take backup for gitlab server(self-hosted)"
  exit 1
}

[ ! -n "$2" ] && cli_help_gitlab
if [ "$2" == "-h" ]; then
  cli_help_gitlab
fi

APP=$1
TIMESTAMP=`date "+%d-%b-%y_%H-%M-%S"`

take_dump() {
  cli_log "Taking Gitlab Dump"
  /opt/gitlab/bin/gitlab-backup create SKIP=registry CRON=1
  cd $BACKUP_DIR/$APP
  cp -rpf /etc/gitlab/gitlab.rb gitlab.rb
  cp -rpf /etc/gitlab/gitlab-secrets.json gitlab-secrets.json
  tar cvzf $APP-$TIMESTAMP.tar.gz *_gitlab_backup.tar gitlab.rb gitlab-secrets.json
  rm -vf *_gitlab_backup.tar gitlab.rb gitlab-secrets.json
  cli_log "Backup Complete"
}

if [ "$2" == "local" ]; then
  take_dump;
elif [ "$2" == "azure" ]; then
  take_dump;
  azure_upload;
fi
